### ISSUE TITLE
Length mismatch error

### ISSUE THREAD

**Issue by diogoalvesderesende** [dafiti/causalimpact#60]
Hi, 

First, I would just like to say I think it is really great that this package exists in Python. Thank you!

While running the following code:
```
#import packages
import yfinance as yf

#define dates
start = "2015-12-28"
treatment = "2018-03-12"
end = "2019-03-11"
end_stock = "2019-03-12"

#get stock price data
stocks = ["FB", "WMT"]
dataset = yf.download(stocks, start = start, end=end_stock, interval = '1wk')

#Getting only the data needed
dataset = dataset.iloc[:,:2]

#getting rid of unneeded level
dataset.columns = dataset.columns.droplevel()

#dropping NA observations
dataset = dataset.dropna()

#getting Causal impact
from causalimpact import CausalImpact

#define periods
pre_period = [start, treatment]
post_period = [treatment, end]

#starting causal impact
impact = CausalImpact(data = dataset, 
                      pre_period = pre_period, 
                      post_period = post_period)
```

I get the following error:
```
Traceback (most recent call last):

  File "<ipython-input-91-902911ae8626>", line 3, in <module>
    post_period = post_period)

  File "C:\Users\diogo\anaconda3\lib\site-packages\causalimpact\main.py", line 235, in __init__
    self._process_posterior_inferences()

  File "C:\Users\diogo\anaconda3\lib\site-packages\causalimpact\main.py", line 311, in _process_posterior_inferences
    self._compile_posterior_inferences()

  File "C:\Users\diogo\anaconda3\lib\site-packages\causalimpact\inferences.py", line 245, in _compile_posterior_inferences
    post_cum_y.index = self._get_cum_index()

  File "C:\Users\diogo\anaconda3\lib\site-packages\pandas\core\generic.py", line 5287, in __setattr__
    return object.__setattr__(self, name, value)

  File "pandas\_libs\properties.pyx", line 67, in pandas._libs.properties.AxisProperty.__set__

  File "C:\Users\diogo\anaconda3\lib\site-packages\pandas\core\series.py", line 401, in _set_axis
    self._data.set_axis(axis, labels)

  File "C:\Users\diogo\anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 178, in set_axis
    f"Length mismatch: Expected axis has {old_len} elements, new "

ValueError: Length mismatch: Expected axis has 54 elements, new values have 53 elements
```
Could you tell me what I am doing wrong?

Thanks in advance!

**Comment by WillianFuks** [comment]
Hi @diogoalvesderesende ,

Thanks for opening this issue! You are right, I also had the same error.

For what it seems, when implementing this package we missed a validation for the beginning of post intervention being bigger than the end of pre-intervetion (you used `treatment` for end and beginning of both, respectively).

I just checked that [this assert](https://github.com/google/CausalImpact/blob/master/R/impact_analysis.R#L134) happens in the original R package but unfortunately doesn't happen in the Python package (I'll fix is ASAP).

For now, please make sure to use the beginning of the post intervention period at least bigger than the end of the pre-intervention. For instance, I used:

    post_period = ["2018-03-19", end]

And then it worked fine.

Let us know if this works for you.

Best,

Will

**Comment by diogoalvesderesende** [comment]
Hey Will,

Thanks for the quick follow up! Much appreciated!

Thanks and best,
Diogo
